{{- if and .Values.api.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
{{ include "superagent.user.annotations" . | indent 4 }}
    descriptions: api
  labels:
{{- include "superagent.labels" . | nindent 4 }}
    component: api
{{ include "superagent.user.labels" . | indent 4 }}
  name: {{ template "superagent.api.fullname" . }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
{{- include "superagent.selectorLabels" . | nindent 6 }}
      component: api
  template:
    metadata:
      annotations:
{{ include "superagent.user.annotations" . | indent 8 }}
      labels:
{{- include "superagent.selectorLabels" . | nindent 8 }}
        component: api
{{ include "superagent.user.labels" . | indent 8 }}
    spec:
      {{- with .Values.image.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.api.pullPolicy }}"
        name: {{ template "superagent.api.fullname" . }}
        {{- if .Values.api.container }}
        {{- if .Values.api.container.command }}
        command: {{ .Values.api.container.command | toJson }}
        {{- end }}
        {{- if .Values.api.container.args }}
        args: {{ .Values.api.container.args | toJson }}
        {{- end }}
        {{- end }}
        env:
        {{- if .Values.api.env }}
          {{- toYaml .Values.api.env | nindent 8 }}
        {{- end }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        # startupProbe:
        #   httpGet:
        #     path: {{ .Values.api.health.startup }}
        #     port: api
        #   failureThreshold: 6
        #   initialDelaySeconds: {{ .Values.api.health.initialDelaySeconds }}
        # livenessProbe:
        #   httpGet:
        #     path: {{ .Values.api.health.liveness }}
        #     port: api
        #   initialDelaySeconds: {{ .Values.api.health.initialDelaySeconds }}
        # readinessProbe:
        #   httpGet:
        #     path: {{ .Values.api.health.ready }}
        #     port: api
        #   initialDelaySeconds: {{ .Values.api.health.initialDelaySeconds }}
        resources:
          {{- toYaml .Values.api.resources | nindent 12 }}
    {{- if and (.Values.nodeSelector) (not .Values.api.nodeSelector) }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.api.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.api.nodeSelector | indent 8 }}
    {{- end }}
    {{- if and (.Values.affinity) (not .Values.api.affinity) }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.api.affinity }}
      affinity:
{{ toYaml .Values.api.affinity | indent 8 }}
    {{- end }}
    {{- if and (.Values.tolerations) (not .Values.api.tolerations) }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.api.tolerations }}
      tolerations:
{{ toYaml .Values.api.tolerations | indent 8 }}
    {{- end }}
{{- end }}