{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "superagent.ui.fullname" . }}
  labels:
{{ include "superagent.labels" . | indent 4 }}
{{- if .Values.ui.service.labels }}
{{ toYaml .Values.ui.service.labels | indent 4 }}
{{- end }}
    component: "ui"
{{- with .Values.ui.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.ui.service.type }}
  {{- if .Values.ui.service.clusterIP }}
  clusterIP: {{ .Values.ui.service.clusterIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      protocol: TCP
      targetPort: http
  selector:
{{ include "superagent.selectorLabels" . | indent 4 }}
    component: "ui"
{{- end }}